### ISSUE TITLE
Use tools.cli to parse parameters

### ISSUE THREAD

**Issue by maoo** [finos/bot-github-chatops#48]
### Description of Problem:

Building new commands with bot-github-chatops implies adding items to the [`commands.clj`](https://github.com/finos-fdx/bot-github-chatops/blob/master/src/bot_github_chatops/commands.clj) file, which currently parses bot input manually.

### Potential Solutions:
https://github.com/clojure/tools.cli delivers a similar functionality but for command-line inputs, which isn't a particularly appropriate format for chat-style interactions.

If there's no library that helps parsing the argument input, a simple library could already help keeping the code leaner and easier to extend.

**Comment by maoo** [comment]
Thanks for the feedback @pmonks . I'll keep the issue open for future references.

**Comment by pmonks** [comment]
In that case can I encourage you to rewrite the issue as a problem statement, rather than a solution statement?  Job story form (see below) is a good technique for ensuring you're stating problems, not solutions.

**Job Story Form**
![image](https://user-images.githubusercontent.com/54865/44688382-f6179100-aa08-11e8-9ff0-aec2de234200.png)

**Comment by pmonks** [comment]
@maoo any updates on this issue?  To my mind this should be closed as `invalid`, since if we're looking to improve the current simplistic parsing of regular-human-to-computer chat interactions, I'd want to look at NLP approaches, not GNU CLI parsing (which is programmer-to-computer).

**Comment by maoo** [comment]
Closing and marking as `invalid` , as suggested above.
